#!/usr/bin/env sh
set -e

echo "Pulling latest code..."
git pull
echo "Deleting local tracked branches that no longer exist in remote..."
git fetch -p
git branch -vv | awk '/: gone]/{print $1}' | xargs git branch -D
echo "Done."
